# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: false

# Setup
title:               'Ad Infinitum'
tagline:             'Tech & Biz thoughts when they happen for as long as they do so.'
description:         ''
url:                 http://adinfinitum.online
baseurl:             '/'
paginate:            5

# About/contact
author:
  name:              Matt Quirion
  url:               https://twitter.com/mquirion
  email:             matt.quirion@gmail.com

# Custom vars
version:             1.0.0
